services:
  ros2_jazzy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-jazzy # resulting image name

    stdin_open: true
    tty: true
    command: /bin/bash # default shell when you attach
    network_mode: host # helps ROS 2 discovery (optional)

    privileged: true
    devices:
      - /dev:/dev

    # — Bind‑mount each git sub‑module into the workspace ————————————
    volumes:
      - ../ros2_ws:/home/ros/base_ws/src/ros2_ws:rw
      - ../ros2-vicon-receiver/vicon_receiver:/home/ros/base_ws/src/vicon_receiver:rw

      # Bash Scripts
      - ../bash_scripts/container:/home/ros/bash_scripts:rw

      # enable mount for gui applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - BASE_WS=/home/ros/base_ws
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
